name: pillreserves release build
on: [push]
jobs:
  build-arch-release:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: update packages
        run: pacman -Syu --noconfirm
      - name: install packages
        run: pacman -S --needed --noconfirm cargo git
      - name: trust repo directory
        run: git config --global --add safe.directory /__w/pillreserves/pillreserves
      - name: check out repository code
        uses: actions/checkout@v2
      - name: fetch dependencies
        run: sh ./cicd/cargo_fetch.sh
      - name: run release build
        run: cargo build --release
      - name: run release tests
        run: cargo test --release
      - name: upload release binary
        uses: actions/upload-artifact@v2
        with:
          name: pillreserves-release
          path: target/release/pillreserves
